[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build || true"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always" 